app:
  name: vobook
  version: 1
  build: 1
  env: dev #dev|test|release

db:
  addr: localhost:26257
  user: root
  password: root
  name: vobook
  log_queries: true

mail:
  server: mail.example.com
  port: 587
  user: user@example.com
  password: password

server:
  host: localhost
  port: 8080

file_storage:
  dir: files

telegram_bot_api: ""

email_verification_lifetime: 2h
auth_token_lifetime: 15m
password_reset_lifetime: 30m

api_base_path: api